/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_GEMINI_API_KEY?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

/** Per-language translation dictionaries generated by the i18n-dictionaries plugin (vite.config.ts) */
declare module 'virtual:i18n-dict/*' {
  const dict: Record<string, string>;
  export default dict;
}
